/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Mar 31 11:57:30 MSK 2021
 */
package com.apsaraconsulting.skyvvaadapter.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.apsaraconsulting.skyvvaadapter.api.dto.AbstractDescribedSObjectBase;
import com.apsaraconsulting.skyvvaadapter.api.dto.SObjectDescription;
import com.apsaraconsulting.skyvvaadapter.api.dto.SObjectDescriptionUrls;
import com.apsaraconsulting.skyvvaadapter.api.dto.SObjectField;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.List;

/**
 * Salesforce DTO for SObject RESTStreamingAPI__c
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@JacksonXmlRootElement(localName = "RESTStreamingAPI__c")
public class RESTStreamingAPI__c extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // Status__c
    private RESTStreamingAPI__c_StatusEnum Status__c;

    @JsonProperty("Status__c")
    public RESTStreamingAPI__c_StatusEnum getStatus__c() {
        return this.Status__c;
    }

    @JsonProperty("Status__c")
    public void setStatus__c(RESTStreamingAPI__c_StatusEnum Status__c) {
        this.Status__c = Status__c;
    }

    // Description__c
    private String Description__c;

    @JsonProperty("Description__c")
    public String getDescription__c() {
        return this.Description__c;
    }

    @JsonProperty("Description__c")
    public void setDescription__c(String Description__c) {
        this.Description__c = Description__c;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Record ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("OwnerId", "Owner ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("Name", "RESTStreamingAPI", "string", "xsd:string", 80, false, false, true, false, false, false, true);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("Status__c", "Status", "picklist", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("Description__c", "Description", "string", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField11);

        description.setLabel("RESTStreamingAPI");
        description.setLabelPlural("RESTStreamingAPIs");
        description.setName("RESTStreamingAPI__c");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setApprovalLayouts("/services/data/v34.0/sobjects/RESTStreamingAPI__c/describe/approvalLayouts");
        sObjectDescriptionUrls1.setCompactLayouts("/services/data/v34.0/sobjects/RESTStreamingAPI__c/describe/compactLayouts");
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/RESTStreamingAPI__c/describe");
        sObjectDescriptionUrls1.setLayouts("/services/data/v34.0/sobjects/RESTStreamingAPI__c/describe/layouts");
        sObjectDescriptionUrls1.setQuickActions("/services/data/v34.0/sobjects/RESTStreamingAPI__c/quickActions");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/RESTStreamingAPI__c/{ID}");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/RESTStreamingAPI__c");
        sObjectDescriptionUrls1.setUiDetailTemplate("https://skyvva32--skyvva15.my.salesforce.com/{ID}");
        sObjectDescriptionUrls1.setUiEditTemplate("https://skyvva32--skyvva15.my.salesforce.com/{ID}/e");
        sObjectDescriptionUrls1.setUiNewRecord("https://skyvva32--skyvva15.my.salesforce.com/a1R/e");
        description.setUrls(sObjectDescriptionUrls1);

        return description;
    }
}
