/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Mar 31 11:57:30 MSK 2021
 */
package com.apsaraconsulting.skyvvaadapter.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.annotation.Generated;

/**
 * Salesforce Enumeration DTO for picklist Status__c
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum RESTStreamingAPI__c_StatusEnum {

    // Closed
    CLOSED("Closed"),
    // Negotiating
    NEGOTIATING("Negotiating"),
    // Open
    OPEN("Open"),
    // Pending
    PENDING("Pending");

    final String value;

    private RESTStreamingAPI__c_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RESTStreamingAPI__c_StatusEnum fromValue(String value) {
        for (RESTStreamingAPI__c_StatusEnum e : RESTStreamingAPI__c_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
